os:
  - Visual Studio 2015

environment:
  matrix:
    - ARCH: x86
      PYTHON: "C:\\Python35"
    - ARCH: x64
      PYTHON: "C:\\Python35-x64"


install:
  - set PATH=%cd%;%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install meson ninja

  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%

build_script:
  - meson build
  - ninja -C build

test_script:
  - ninja -C build test
