os:
  - Visual Studio 2017

environment:
  matrix:
    - ARCH: x86
      PYTHON: "C:\\Python37"
    - ARCH: x64
      PYTHON: "C:\\Python37-x64"


install:
  - chcp 65001
  - set PYTHONIOENCODING=utf-8
  - set PATH=%cd%;%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install meson ninja

  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%

build_script:
  - meson build
  - ninja -C build

# Currently fails, possibly stdin/stdout encoding issue.
#test_script:
#  - ninja -C build test
