dist: xenial
sudo: true

language: c

matrix:
  include:
    - os: linux
      after_success:
        - bash .ci/deploy-docs.sh

    - os: linux
      compiler: clang

    - os: osx
      before_install:
        - export XML_CATALOG_FILES="/usr/local/etc/xml/catalog" # for the docs

install:
  - pip3 install meson ninja

before_script:
  - meson -Ddocs=true build

script:
  - ninja -C build
  - ninja -C build test

addons:
  apt:
    packages:
      - libfreetype6-dev
      - libharfbuzz-dev
      - libfribidi-dev
      - gtk-doc-tools
      - python3-pip
      - python3-setuptools
  homebrew:
    packages:
      - freetype
      - fribidi
      - gtk-doc
      - harfbuzz
      - python
